

print("Friend A: Hey, did you finish your homework?")
print("Friend B: Not yet, I got distracted watching cricket.")
print("Friend A: I knew it! Which match?")
print("Friend B: Yesterday’s IPL game, it was amazing.")
print("Friend A: I missed it, who won?")
print("Friend B: Our team pulled off a last-over victory")
print("Friend A: That sounds thrilling.")
print("Friend B: Yeah, my dad and I were shouting at the TV.")
print("Friend A: Classic! I was busy coding a project.")
print("Friend B: Oh really, what project?")
print("Friend A: Just practicing Python string concatenation.")
print("Friend B: Nice, I’m still learning the basics.")
print("Friend A: Don’t worry, you’ll get better with practice.")
print("Friend B: Thanks, Bro!.")
print("Friend A: By the way, are you free this weekend?")
print("Friend B: yes, what’s the plan?")
print("Friend A: Let’s go cycling around the park.")
print("Friend B: Sounds fun, I’ll bring my new bike.")
print("Friend A: Great, we can race a little.")
print("Friend B: Haha, you’ll probably win.")
print("Friend A: Not sure, you’ve been practicing more.")
print("Friend B: True, but you’re faster on turns.")
print("Friend A: We’ll see! After that, maybe grab some snacks.")
print("Friend B: Perfect, I know a shop nearby.")
print("Friend A: cool")
print("Friend B: I’m excited already.")
print("Friend A: same here, it’ll be a good break.")
print("Friend B: absolutely, we need it after all the studying.")
print("Friend A: Exactly, balance is important.")
print("Friend B: Alright then, it’s a plan!")
print("Friend A: Done, I’ll text you the details later.")
print("Friend B: see you soon!")
